### ISSUE TITLE
Print a link to package.json while displaying errors.

### ISSUE THREAD

**Issue by kwangure** [bluwy/publint#39]
`publint` prints errors in `package.json` in the format `pkg.exports["./path/to/exports"].property has error X`. A minor quality of life improvement would be printing the `package.json` path with line numbers such that you can Ctrl+Click to the error in VS Code and friends.

**Comment by bluwy** [comment]
Good idea. Displaying the line numbers is tricky though since we're parsing the JSON and it doesn't provide the line numbers. We could technically assume that it's properly indented so we can guess the line number, but that feels a bit complex.

In that case, I'm slightly leaning to keeping it simple so the output is cleaner too.

**Comment by kwangure** [comment]
For unique substrings, try https://github.com/Rich-Harris/locate-character. Otherwise just link to the `package.json` without an exact location.

**Comment by bluwy** [comment]
Yeah I was thinking of just linking the `package.json`, but in most case you can easily find it yourself as it's in your own project. Trying to prevent printing it for each message/errors too as the path can get noisy.

**Comment by bluwy** [comment]
I think it's better to keep it simple for now. We can revisit again if there's more request for this.
