### ISSUE TITLE
packages that doesn't show in search will be shown as not found

### ISSUE THREAD

**Issue by sapphi-red** [bluwy/publint#6]
For example, [`fs` package is not shown in search](https://www.npmjs.com/search?q=fs) but [exists](https://www.npmjs.com/package/fs).

Currently publint shows this as not found: https://publint.bjornlu.com/fs

**Comment by bluwy** [comment]
I think this would be a limitation for now as I'm using https://registry.npmjs.org/-/v1/search?text=fs&size=1 to get the `latest` tag version so that we can fetch the package tar. 

I could use https://registry.npmjs.org/fs for correctness, but I found this packument to be quite large even with the [advised headers](https://github.com/npm/registry/blob/master/docs/responses/package-metadata.md#package-metadata), so it's not worth the fetch.

You could access https://publint.bjornlu.com/fs@0.0.1-security though if you know the version. Closing this one for now.

**Comment by bluwy** [comment]
Actually we could do a secondary fetch if the first one fails, so it could work too 🤔

**Comment by sapphi-red** [comment]
It seems we can use `/{pkgName}/latest`.
https://github.com/npm/registry/blob/master/docs/REGISTRY-API.md#getpackageversion

https://registry.npmjs.org/fs/latest
https://registry.npmjs.org/typescript/latest

**Comment by bluwy** [comment]
Oh that is a lot better 👀 I just pushed a fix with my idea above, but yours seem simpler

**Comment by bluwy** [comment]
Alright 715fd0f should be a lot simpler now. Thanks for digging out the API, that somehow went pass me.

**Comment by sapphi-red** [comment]
Thanks for implementing 💙
