### ISSUE TITLE
Warning message displays error

### ISSUE THREAD

**Issue by btea** [bluwy/publint#71]
The warning message is displayed in the wrong location.

![image](https://github.com/bluwy/publint/assets/24516654/bb771d36-60a9-45ef-90d0-3b178919d62e)

**Comment by bluwy** [comment]
That's because it refers to deep importing the package, like `import "isobject/index.mjs"`, because packages without `"exports"` implicitly expose all files.

It's a little different to the `"module"` field for this package specifically, because bundlers that support `"module"` force treats the format as ESM always. So there's no problem there.

So I think while it's a bit off in this case, it's technically correctly located 🤔

**Comment by btea** [comment]
OK, thank you for your explanation. 👍
